import json
import os
import uuid
from datetime import datetime, timezone
from decimal import Decimal

import boto3
from openai import OpenAI

from tools.writing_tools import analyze_text


REGION = os.environ.get(
    "AWS_REGION",
    "ap-south-1"
)

MODEL_ID = os.environ.get(
    "BEDROCK_MODEL_ID",
    "openai.gpt-oss-120b"
)

CONVERSATIONS_TABLE = os.environ["CONVERSATIONS_TABLE"]
MESSAGES_TABLE = os.environ["MESSAGES_TABLE"]
NOTIFICATION_QUEUE_URL = os.environ["NOTIFICATION_QUEUE_URL"]

# OpenAI client picks up OPENAI_API_KEY and OPENAI_BASE_URL
# from environment variables automatically.
client = OpenAI()

dynamodb = boto3.resource(
    "dynamodb",
    region_name=REGION
)

sqs = boto3.client(
    "sqs",
    region_name=REGION
)

conversations_table = dynamodb.Table(CONVERSATIONS_TABLE)
messages_table = dynamodb.Table(MESSAGES_TABLE)


def to_ddb(value):
    """Recursively convert floats to Decimal for DynamoDB."""
    if isinstance(value, float):
        return Decimal(str(value))
    if isinstance(value, dict):
        return {k: to_ddb(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_ddb(v) for v in value]
    return value


def response(status_code, body):
    return {
        "statusCode": status_code,
        "headers": {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
        },
        "body": json.dumps(body),
    }


def get_user_id(event):
    claims = (
        event
        .get("requestContext", {})
        .get("authorizer", {})
        .get("jwt", {})
        .get("claims", {})
    )

    user_id = claims.get("sub")

    if not user_id:
        raise ValueError("Authenticated user not found")

    return user_id


def invoke_model(user_message, analysis):
    system_prompt = (
        "You are an AI writing assistant. "
        "Your job is to help users improve writing. "
        "You have access to deterministic measurements generated by Python analysis tools. "
        "Use those measurements when giving feedback. Do not invent measurements. "
        "When useful, explain: word count, readability, weak words, long sentences, repeated words. "
        "Give practical, specific recommendations. "
        "The user may ask for: writing review, rewriting, grammar improvement, "
        "professional tone, technical writing, concise writing, readability improvement."
    )

    user_prompt = (
        f"Analyze the following writing.\n\n"
        f"WRITING:\n{user_message}\n\n"
        f"DETERMINISTIC ANALYSIS:\n{json.dumps(analysis, indent=2)}\n\n"
        f"Return a useful response for the user."
    )

    result = client.responses.create(
        model=MODEL_ID,
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )

    return result.output_text


def save_message(
    conversation_id,
    role,
    content,
    analysis=None
):
    timestamp = datetime.now(timezone.utc).isoformat()

    item = {
        "conversation_id": conversation_id,
        "created_at": timestamp,
        "role": role,
        "content": content,
    }

    if analysis is not None:
        item["analysis"] = to_ddb(analysis)

    messages_table.put_item(Item=item)

    return timestamp


def save_conversation(user_id, conversation_id, title):
    timestamp = datetime.now(timezone.utc).isoformat()

    conversations_table.put_item(
        Item={
            "user_id": user_id,
            "conversation_id": conversation_id,
            "title": title[:100],
            "created_at": timestamp,
            "updated_at": timestamp,
        }
    )


def publish_notification(user_id, conversation_id):
    sqs.send_message(
        QueueUrl=NOTIFICATION_QUEUE_URL,
        MessageBody=json.dumps({
            "event": "chat.completed",
            "user_id": user_id,
            "conversation_id": conversation_id,
        })
    )


def lambda_handler(event, context):

    try:

        user_id = get_user_id(event)

        body = json.loads(
            event.get("body") or "{}"
        )

        message = body.get("message", "").strip()

        if not message:
            return response(
                400,
                {"error": "message is required"}
            )

        conversation_id = (
            body.get("conversation_id")
            or str(uuid.uuid4())
        )

        if not body.get("conversation_id"):
            save_conversation(
                user_id,
                conversation_id,
                message[:80]
            )

        analysis = analyze_text(message)

        save_message(
            conversation_id,
            "user",
            message,
            analysis
        )

        ai_response = invoke_model(
            message,
            analysis
        )

        save_message(
            conversation_id,
            "assistant",
            ai_response
        )

        publish_notification(
            user_id,
            conversation_id
        )

        return response(
            200,
            {
                "conversation_id": conversation_id,
                "message": ai_response,
                "analysis": analysis,
            }
        )

    except Exception as exc:

        print(f"ERROR: {type(exc).__name__}: {exc}")

        return response(
            500,
            {"error": "Unable to process chat"}
        )
